name: Bug
description: An unexpected problem or behavior
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        You can attach the `triage` label to your issue if you want it to be discussed in the next [planning meeting](https://docs.metal-stack.io/stable/developers/planning-meetings/).
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
