name: Question
description: General question or support requested
type: Question
body:
  - type: textarea
    id: question
    attributes:
      label: Description
      placeholder: You have a general question or need support? Raise your question here.
      description: Please consider reaching out to our community Slack channel if it's just something small.
    validations:
      required: true
